### PR TITLE
Updates to the CLI

### PR DESCRIPTION
**Pull request by stuartmcalpine**
Update the CLI for v0.4.0.
- Update the test structure so its pure python and no bash
- Add ability to delete datasets through the CLI
- Update the docs for the CLI

### CODE REVIEW

**Comment by JoanneBogart** [comment]
Does the old `cli/cli.py` differ much from the new `dataregistry_cli/cli.py` ?

**Comment by stuartmcalpine** [comment]
> Does the old `cli/cli.py` differ much from the new `dataregistry_cli/cli.py` ?

No its the same, just the parsing of the CLI commands is put into its own function. 

The "only" difference is the CI, where the bash parts for entering the data into the registry are removed, and its all done through the `test_end_to_end_cli.py` file. I had to modify the `dataregistry_cli/cli.py` file into multiple functions so I could call them more easily for the CI.

I will leave these changes as they are (just updating the CI for the CLI) for the PR, and then make a new PR for adding `delete` to the CLI, so its easier to review.

**Comment by stuartmcalpine** [comment]
p.s the Docs CI fails here at the moment, that will be fixed when the `v0.4.0` docs branch is merged in

**Review by JoanneBogart — APPROVED** [review]
This looks fine.
I have one somewhat extraneous comment: python 3.9 is by now pretty old. The standard kernels Heather maintains are 3.10 and newer LSST stacks I believe 3.11.  Should we move to at least 3.10 here?

**Pull request merged**
