### PR TITLE
Added schema and backend to relative path

### PR DESCRIPTION
**Pull request by stuartmcalpine**

### CODE REVIEW

**Review by JoanneBogart — APPROVED** [review]
It looks fine, but I think we should mark this change with a new version.  If we had any real users, it would break things (they wouldn't be able to retrieve old files with the new code).  Maybe update to 0.3.0 ?
I'm calling it "approved" because I don't need to review again.

**Comment by stuartmcalpine** [comment]
@JoanneBogart Ah yes didn't think about this, should bump the version.

Should we then reset the data dir? or create a new root dir from this version on?

**Comment by JoanneBogart** [comment]
The last time I checked no one had anything in the data dir except us.  If that's still true, I think we can just wipe everything that's there.
We should also notify users (probably no one else except Joe at this point) that 
* they should update their code
* if they've registered items in a private area using the old code, they won't be accessible with the new code.
Formally that means we should increase the major version number, but since we haven't yet made a production release maybe that's not necessary.

**Comment by stuartmcalpine** [comment]
ok i have updated to v0.3.0.

I'll let Joe know, but i think we can safely wipe that dir

**Comment by JoanneBogart** [comment]
On further thought, maybe just leave it, at least for the time being. 
I've made a new directory /global/cdfs/cdirs/desc-co/dataregistry
That should be the new default in registrar.py

**Comment by JoanneBogart** [comment]
If someone is using SQLite for the db, there is no schema, so data for all sqlite users will be lumped together in the same area. Does the code need to be aware of that (handle non-schema gracefully)? And could it cause problems for users?  I'm guessing as a practical matter it won't. I doubt we'll have many users working at NERSC but using an SQLite db

**Pull request closed without merging**
