### PR TITLE
Update queries

### PR DESCRIPTION
**Pull request by stuartmcalpine**
Make more options for querying

- There is now a `~=` query operator that can utalise the `.ilike` filter to   allow non-case-sensitive filering with wildcards (i.e., the `%` character).
- `dregs ls` can now filter on the dataset name, including `%` wildcards, using   the `--name` option.
- `dregs_ls` can return arbitrary columns using the `--return_cols` option

### CODE REVIEW

**Review by JoanneBogart — CHANGES_REQUESTED** [review]
I left one inline comment about mixing case-insensitivity with wildcard parsing.
A second issue has to do with escaping wildcards.  Postgres treats both `%` and `_` as potential wildcards.  I believe sqlalchemy just passes the string as-is to Postgres. One can specify an escape character (by default `\`).  I would say we should go with the default escape character - it's already something we exclude from names. Then before using .like or .ilike any underscore characters should be escaped (otherwise an underscore matches any single character; I think we can do without that capability). Maybe we also need to look for backslashes and, if found, escape them as well, but it's unlikely to come up except possibly in a field like `description`.
I'm also wondering whether we should use `*` as the wildcard character rather than `%`.  One advantage is it's already excluded from names (but not from all string fields). The other is that people are used to it as a wildcard character. If we use it, the procedure would be
- escape all `_` and `%`
- replace `*` with `%`
- invoke `.like` or `.ilike` as appropriate
There still is an issue with either `*` or `%` existing in the string when it's not intended to be a matching character.  Maybe we just have to disallow "like" comparisons for all but a carefully-selected set of string columns.

**Comment by stuartmcalpine** [comment]
- Added the `~==` operator for case sensitive wildcard searches
- Changed the wildcard operator from `%` to `*` (and `_` is also escaped)

> There still is an issue with either * or % existing in the string when it's not intended to be a matching character. Maybe we just have to disallow "like" comparisons for all but a carefully-selected set of string columns.

Can either just leave it, or limit the columns. There is no limit on the columns currently, I don't know how `ilike` works on non-string columns...

I'd imagine this will primarily be used on the `name` column.

**Comment by JoanneBogart** [comment]
I'm thinking it should only apply to a limited set of columns, but more than just `name`.  I'd include at least `owner` and `relative_path`.  Maybe more.  I'll take a look.

**Comment by stuartmcalpine** [comment]
> I'm thinking it should only apply to a limited set of columns, but more than just name. I'd include at least owner and relative_path. Maybe also version_string, creator_uid and access_api

Looks like the partial match can only be done for string columns, so I've added a restriction to only allow the feature for certain string columns

**Pull request merged**
