### PR TITLE
change dependency from pyaml to pyyaml

### PR DESCRIPTION
**Pull request by JoanneBogart**
See if substituting pyyaml for pyaml dependency causes any problems

### CODE REVIEW

**Comment by JoanneBogart** [comment]
@stuartmcalpine is there some reason we need `pyaml` (which depends on `pyyaml` rather than just `pyyaml`?  When I uploaded a build to PyPI and then tried to install I ran into problems with `pyyaml` which went away when I switched to `pyyaml`.

**Comment by JoanneBogart** [comment]
There is already a project in production PyPI with a very similar name, so `dataregistry` would not be acceptable.  Heather suggested prepending `lsstdesc`, which has been done in other cases, so that's what I've done.  So far I've only uploaded to test PyPI. See https://test.pypi.org/project/dataregistry/

**Comment by stuartmcalpine** [comment]
I didn't know  there was different yaml packages, if the new one works, no problem with me.

This is just to change the name of the package on PyPi to `lsstdesc-dataregistry`, or would we also prefer to change the name of the installed package also?

**Comment by JoanneBogart** [comment]
> This is just to change the name of the package on PyPi to lsstdesc-dataregistry, or would we also prefer to change the name of the installed package also?

For now I only wanted to change the name of the package on PyPI because I'm not sure what might be entailed if we go further.   I don't want to have to change `import` statements.  I'm somewhat leery of changing the repo name in GitHub.  What are the options?

**Comment by stuartmcalpine** [comment]
Whilst it would be nice and consistent to keep the package names consistent between pypi and what gets installed, I think its fine to just change the name on pypi.

I think keeping the repo name is also fine, as it is local to the parent lsstdesc repo.

**Review by stuartmcalpine — APPROVED** [review]

**Pull request merged**
