### PR TITLE
Fix bug where we have not specified any properties

### PR DESCRIPTION
**Pull request by stuartmcalpine**
When we do a query with `property_names=None` we were crashing, fixed this.

### CODE REVIEW

**Comment by JoanneBogart** [comment]
According to the header comments in `find_datasets` 

> If property_names is None, return all properties from the dataset table
        (only). Otherwise, return the property_names columns for each
        discovered dataset (which can be from multiple tables via a join).
        
I prefer this behavior.  If someone really wants **everything** they should say so explicitly.
Then I don't know that _parse_selected_columns needs to be called at all in this case. One could just say
`if not property_names:
    tables_required = ["dataset"]
else:
     tables_required, _, _ = self._parse_      ....  `

In the code as it currently stands, that would eliminate any possibility of `_parse_selected_columns` being called with  `column_names == None`. But it's still a good idea to handle the case of `column_names == None` somehow.      One possibility is to just not allow it (e.g. raise ValueError).

**Review by JoanneBogart — CHANGES_REQUESTED** [review]
I prefer a different approach to fixing this.  See other comments.

**Comment by stuartmcalpine** [comment]
I've modified it to as suggested.

This was more in preparation for the return type, where I need the column objects (to create SELECT xxx as xxx), which can be done through `_parse_selected_columns`, but thats where I found the None bug.

We can come back to it in the other pull request

**Review by JoanneBogart — APPROVED** [review]
The code looks good; thanks.   Please change the docstring for `_parse_selected_columns` so it correctly describes the behavior for column_names == None before merging - no need for another review.

**Pull request merged**
