### PR TITLE
Add dataset status and move/delete/archive information

### PR DESCRIPTION
**Pull request by stuartmcalpine**
Update the dataset table to include:

- status (-1: Invalid (e.g., copy data failed during creation), 1: Valid, 2: Archived, 3: deleted)
- archive_date (When archived)
- archive_path (Where archived to)
- delete_date (when deleted)
- delete_uid (who deleted)
- move_date (when last move)

Any more?

### CODE REVIEW

**Comment by JoanneBogart** [comment]
I don't think these attributes (invalid, valid, archived, deleted) are exactly mutually exclusive.  We might want to treat the status field as a bit mask up.  Possible attributes of the dataset are
invalid  (registration failed; there may be a file or files on disk but they are useless)
valid     (successful registration and file(s) exist on disk)
backed up  (successful registration and file(s) backed up)
deleted  (no files on disk)
or maybe carry this a bit further and subdivide "valid"  into orthogonal attributes "valid" (registration successful) and "live" (usable files exist on disk).
To be further discussed.

**Comment by stuartmcalpine** [comment]
Have updated the dataset `status` field to be a bitmask. So now any combination of `valid`, `deleted`, `archived` are available with a single digit.

Have also added a CI test for the functions.

**Comment by JoanneBogart** [comment]
Some questions:
Do we want a move_uid?
Does "deleted" imply "not valid"?   What about "moved"?

Maybe we wait until these things are fully implemented before worrying too much about the exact form of these fields.   
But in any case I think we should wait until the "reformat register" PR is approved (and merged with to version placeholder branch) before merging in this one.

**Review by JoanneBogart — APPROVED** [review]
As we implement additional features we might want to modify things a bit, but this looks fine for now.

**Pull request merged**
