### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by stuartmcalpine**

### CODE REVIEW

**Comment by stuartmcalpine** [comment]
I've changed the logo to remove dregs.

ill also go through and change some of the primary front facing things to remove the reference.

i dont see a big issue with leaving it as a short hand for dataregstiry deeper in the docs and the name of the CLI command?

**Comment by JoanneBogart** [comment]
I think it's fine to keep DREGS for the CLI command, but I would rather not use it as shorthand for the actual facility anywhere.

**Comment by stuartmcalpine** [comment]
@JoanneBogart i think i've removed all mention of dregs, other than it being the CLI command.

anywhere i've missed?

**Review by JoanneBogart — APPROVED** [review]
Wow! This is very comprehensive.  Thank you!

**Pull request merged**
