### PR TITLE
Added return type options

### PR DESCRIPTION
**Pull request by stuartmcalpine**
User can now ask for how the query data is returned, 
- CursorResult (SQLAlchemy, default)
- Pandas dataframe
- Property dict

### CODE REVIEW

**Review by JoanneBogart — CHANGES_REQUESTED** [review]
This fails for DataFrame and dict if someone asks for columns with the same name from different tables, e.g. `execution.name` and `dataset.name`.    I'm not sure what is the best approach.  One possibility is to modify the select statement, e.g.
```select dataset.name as "dataset.name"```
 but does that mean we should be doing this all the time? 
 (So far I haven't found a way to express "as" in sqlalchemy other than providing the SQL text, but it's probably there somewhere.)

**Comment by stuartmcalpine** [comment]
I've changed the querying to use the `label` method, to mean that all queries go like

select dataset.name as "dataset.name", execution.name as "exectuion.name" from....

So now the dataframes and property_dicts will have `dataset.name` etc as their column names, so no more worries about ambiguity.

The only slight downside is if you want to use the SQLAlchemy cursor result objects. The results are objects that you get the properties via something like `r.name`, but now we have a extra dot in the names, it doesn't like that. So you have to do `getattr(r, "dataset.name")`. I would however think that the dict as the default return type  is a better option anyway.

For now the tests use the `getattr` function and cursorresult objects.

what do you think?

**Comment by JoanneBogart** [comment]
I need to try it out, hopefully in the next day or two, but I tend to agree that dict will make a better default than sqlalchemy cursor.

**Review by JoanneBogart — APPROVED** [review]
I made 3 minor comments; please take a look at them.  I don't think it needs another review.
If sqlalchemy CursorResult is problematic, perhaps we should let `property_dict` be the default. Also explain somewhere what special handling CursorResult might need.

**Pull request merged**
